import Head from "next/head";

import styles from "@/styles/Home.module.css";
import axios from "axios";
import { useEffect, useState } from "react";
export default function Home() {
  const [invoices, setInvoices] = useState([]);
  const [newInvoice, setNewInvoice] = useState({
    lineNo: "",
    productName: "",
    unitNo: "",
    price: "",
    quantity: "",
    expiryDate: "",
  });
  useEffect(() => {
    const fetchProducts = async () => {
      const response = await axios.get("http://localhost:5000/Invoices");
      console.log(response);
      setInvoices(response.data);
      console.log(invoices);
    };

    fetchProducts();
  }, []);

  const handleDelete = async (id) => {
    await axios.delete(`http://localhost:5000/Invoices/${id}`);
    const fetchProducts = async () => {
      const response = await axios.get("http://localhost:5000/Invoices");
      console.log(response);
      setInvoices(response.data);
    };
    fetchProducts();
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    await axios.post("http://localhost:5000/Invoices", newInvoice);
    const fetchProducts = async () => {
      const response = await axios.get("http://localhost:5000/Invoices");
      console.log(response);
      setInvoices(response.data);
    };
    fetchProducts();
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Hello</h1>

      <div>
        <h1>List of products</h1>
        <ul>
          {invoices.map((e) => (
            <>
              <li>
                {e.productName} - {e.price} - {e.quantity} - {e.total} -{" "}
                {e.lineNo}
              </li>
              <button onClick={() => handleDelete(e._id)}>Delete</button>
            </>
          ))}
        </ul>
      </div>

      <div>
        <h1>Add products</h1>
        <form onSubmit={handleSubmit}>
          <input
            type="text"
            placeholder="product name"
            value={newInvoice.productName}
            onChange={(e) =>
              setNewInvoice({ ...newInvoice, productName: e.target.value })
            }
          />
          <input
            type="number"
            placeholder="Line Number"
            value={newInvoice.lineNo}
            onChange={(e) =>
              setNewInvoice({ ...newInvoice, lineNo: e.target.value })
            }
            required
          />

          <input
            type="text"
            placeholder="Unit ObjectId"
            value={newInvoice.unitNo}
            onChange={(e) =>
              setNewInvoice({ ...newInvoice, unitNo: e.target.value })
            }
            required
          />

          <input
            type="number"
            placeholder="Price"
            value={newInvoice.price}
            onChange={(e) =>
              setNewInvoice({ ...newInvoice, price: e.target.value })
            }
            required
          />

          <input
            type="number"
            placeholder="Quantity"
            value={newInvoice.quantity}
            onChange={(e) =>
              setNewInvoice({ ...newInvoice, quantity: e.target.value })
            }
            required
          />

          <input
            type="date"
            placeholder="Expiry Date"
            value={newInvoice.expiryDate}
            onChange={(e) =>
              setNewInvoice({ ...newInvoice, expiryDate: e.target.value })
            }
            required
          />

          <button type="submit">add</button>
        </form>
      </div>
    </>
  );
}
